name: ddm_env
channels:
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - cpuonly
  - dask
  - jpype1>0.6
  - matplotlib
  - nd2reader
  - notebook
  - numba
  - numpy
  - pims
  - pip
  - pip:
      - nd2==0.3.0
      - git+https://github.com/schuetzgroup/sdt-python.git@17.3
  - pyfftw
  - python=3.8
  - python-graphviz
  - pytorch
  - readlif
  - scikit-image
  - scipy
  - tensorflow
  - torchvision
  - tqdm
  - xarray
