name: ddm_env
channels:
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - dask
  - dask-image
  - ipympl
  - ipywidgets
  - jpype1=>0.6.1
  - matplotlib
  - nd2reader
  - notebook
  - numba
  - numpy
  - pims
  - pip
  - pip:
      - nd2==0.3.0
      - git+https://github.com/schuetzgroup/sdt-python.git@17.3
  - psutil
  - pyfftw
  - python=3.8
  - python-graphviz
  - readlif
  - scikit-image
  - scipy
  - tqdm
  - xarray
