name: Build and test Python package

on:
  push:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for manually running CI Build workflow
        required: False
        default: ""

jobs:
  python_tests:
    name: tests / python-3.8 / ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python info
        run: |
          which python
          python --version
      - name: Build package and create dev environment
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Test with coverage
        run: |
          pytest --cov --cov-report=xml
      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true

  build_pypi:
    name: Test pypi build
    runs-on: ubuntu-latest
    needs: python_tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python info
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade build
      - name: Build package
        run: |
          python -m build
      - name: Check package
        run: |
          pip install twine
          python -m twine check dist/*
